USE master
GO
USE OnlineShop
GO
DROP DATABASE OnlineShop
CREATE DATABASE OnlineShop
ON 
(NAME = 'OnlineShopData',
FILENAME = 'D:\Course 3\Базы данных\Курсач\OnlineShopData.mdf')
LOG ON (NAME = 'OnlineShopData_Log',
FILENAME = 'D:\Course 3\Базы данных\Курсач\OnlineShopData.ldf')
-- admin table
DROP TABLE admins
CREATE TABLE admins
(
	login_admin varchar(50) NOT NULL PRIMARY KEY,
	password_admin varchar(16) NOT NULL
)
SELECT * FROM admins
INSERT INTO admins
VALUES ('fanisnigamad@yandex.ru', 'adminpassword!')
INSERT INTO admins
VALUES ('00', '00')
--

DROP TABLE COMMODITY
CREATE TABLE COMMODITY
(
	COMM_ID int IDENTITY(1,1) NOT NULL,
	CODE_OF_COM char(10) NOT NULL PRIMARY KEY,
	NAME_OF_COM varchar(100) NOT NULL,
	PRICE money NOT NULL,
	CODE_OF_STOR char(10) NOT NULL,
	COUNT_OF_COM int NOT NULL,
	FOREIGN KEY (CODE_OF_STOR) REFERENCES STORAGE(CODE_OF_STOR),
	CHECK (COUNT_OF_COM>=0),
	CHECK (LEN(CODE_OF_COM)=10)
)
sp_help COMMODITY
sp_help STORAGE
sp_help CONSUMER

delete from PURCHASE where EMAIL = 'fanisnigamad@yandex.ru' and CODE_OF_COM = 'K7FN6BF7O9'

DROP TABLE STORAGE
CREATE TABLE STORAGE
(
	STOR_ID int IDENTITY(1,1) NOT NULL,
	CODE_OF_STOR char(10) NOT NULL PRIMARY KEY,
	ADDRESS_OF_STOR varchar(100) NOT NULL,
	CHECK(LEN(CODE_OF_STOR)=10)
)
DROP TABLE CONSUMER
CREATE TABLE CONSUMER
(
	CONSUMER_ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(100) NOT NULL PRIMARY KEY,
	FULL_NAME varchar(100) NOT NULL,
	ADDRESS_OF_RESID varchar(100) NOT NULL
)
DROP TABLE PURCHASE
CREATE TABLE PURCHASE
(
	PURCHASE_ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(100) NOT NULL,
	CODE_OF_COM char(10) NOT NULL,
	DATE_OF_PURCHASE datetime NOT NULL,
	DATE_OF_RECEIPT datetime NULL,
	PRIMARY KEY(EMAIL, CODE_OF_COM, DATE_OF_PURCHASE),
	FOREIGN KEY(EMAIL) REFERENCES CONSUMER(EMAIL),
	FOREIGN KEY(CODE_OF_COM) REFERENCES COMMODITY(CODE_OF_COM),
	CHECK (LEN(CODE_OF_COM)=10),
	CHECK (DATE_OF_RECEIPT>DATE_OF_PURCHASE)
	
)
ALTER TABLE COMMODITY
	DROP CONSTRAINT FK_CODE_OF_STOR
ALTER TABLE PURCHASE
	DROP CONSTRAINT FK_EMAIL 
ALTER TABLE PURCHASE
	DROP CONSTRAINT FK_CODE_OF_COM 

ALTER TABLE COMMODITY
	ADD CONSTRAINT FK_CODE_OF_STOR
	FOREIGN KEY (CODE_OF_STOR) REFERENCES STORAGE(CODE_OF_STOR)
ALTER TABLE PURCHASE
	ADD CONSTRAINT FK_EMAIL 
	FOREIGN KEY (EMAIL) REFERENCES CONSUMER(EMAIL)
ALTER TABLE PURCHASE
	ADD CONSTRAINT FK_CODE_OF_COM 
	FOREIGN KEY (CODE_OF_COM) REFERENCES COMMODITY(CODE_OF_COM)

SELECT * FROM STORAGE
INSERT INTO STORAGE
VALUES ('00K7HRUV6E', 'г. Москва, ул. Третьякова 33')
INSERT INTO STORAGE
VALUES ('00K34RUV6E', 'г.Оренбург, ул. Карла Маркса 17')
INSERT INTO STORAGE
VALUES ('00K34RII6E', 'г.Казань, ул. Гагарина 10а')

SELECT * FROM CONSUMER
INSERT INTO CONSUMER
VALUES ('fanisnigamad@yandex.ru', 'Nigamadyanov Fanis', 'Kazan')
INSERT INTO CONSUMER
VALUES ('forexample@gmail.com', 'Unknown User', 'Moscow')
INSERT INTO CONSUMER
VALUES ('alexander2012@gmail.com', 'Alexander Glushko', 'Saratov')

SELECT * FROM COMMODITY
INSERT INTO COMMODITY
VALUES ('K7FN6BF7O9', 'Футбольный мяч', 1000, '00K7HRUV6E', 115)
INSERT INTO COMMODITY
VALUES ('K79J72BFO9', 'Воздушный шар', 5, '00K34RUV6E', 1150)
INSERT INTO COMMODITY
VALUES ('K79J80BFO9', 'Боксерские перчатки', 1500, '00K34RII6E', 15)

SELECT * FROM PURCHASE
INSERT INTO PURCHASE
VALUES ('fanisnigamad@yandex.ru', 'K7FN6BF7O9','2022-08-10 12:12:08','2022-08-11 12:12:08')
INSERT INTO PURCHASE
VALUES ('alexander2012@gmail.com', 'K79J72BFO9','2022-09-10 10:12:18','2022-09-10 20:00:08')


SELECT CONSUMER.FULL_NAME, COMMODITY.NAME_OF_COM, PURCHASE.DATE_OF_PURCHASE,PURCHASE.DATE_OF_RECEIPT 
FROM (PURCHASE INNER JOIN CONSUMER ON CONSUMER.EMAIL=PURCHASE.EMAIL) INNER JOIN COMMODITY ON PURCHASE.CODE_OF_COM=COMMODITY.CODE_OF_COM WHERE NAME_OF_COM like '%ут%'

SELECT * FROM PURCHASE INNER JOIN CONSUMER ON CONSUMER.EMAIL=PURCHASE.EMAIL